# Generated by Django 2.2.12 on 2020-06-21 18:31

from django.db import migrations
import djongo.models.fields
import historique.models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='triplets',
        ),
        migrations.AddField(
            model_name='csvproject',
            name='table_file',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=historique.models.File, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='csv_data',
            field=djongo.models.fields.ArrayField(blank=True, model_container=historique.models.CsvProject, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='html_data',
            field=djongo.models.fields.ArrayField(blank=True, model_container=historique.models.HtmlProject, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='text_data',
            field=djongo.models.fields.ArrayField(blank=True, model_container=historique.models.TextProject, null=True),
        ),
        migrations.AddField(
            model_name='textproject',
            name='p_file',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=historique.models.File, null=True),
        ),
    ]
