# Generated by Django 2.2.12 on 2020-06-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvproject',
            name='separator',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
