# Generated by Django 2.2.12 on 2020-06-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated',
        ),
    ]
