# Generated by Django 2.2.12 on 2020-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_rdfclass_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriety',
            name='uri',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
