# Generated by Django 2.2.12 on 2020-06-26 13:09

from django.db import migrations, models
import djongo.models.fields
import historique.models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_auto_20200626_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tables', djongo.models.fields.ArrayField(blank=True, model_container=historique.models.CsvProject, null=True)),
                ('paragraphs', djongo.models.fields.ArrayField(blank=True, model_container=historique.models.TextProject, null=True)),
            ],
        ),
    ]
