# Generated by Django 2.2.13 on 2020-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_auto_20200621_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
