# Generated by Django 2.2.13 on 2020-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_auto_20200627_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
    ]
