# Generated by Django 2.2.13 on 2020-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0003_project_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='converted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
